export enum OrderType {
    PICKUP="PICKUP",
    DELIVERY="DELIVERY"
}

export enum OrderStatus {
    PENDING = "PENDING",
    CONFIRMED = "CONFIRMED",
    PREPARING = "PREPARING",
    DELIVERING = "DELIVERING",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    RECEIVED = "RECEIVED",
    SHIPPING = "SHIPPING",
    DELIVERED = "DELIVERED"
}